pdf:
  encoding:         'UTF-8'
  page-size:        'Letter'
  orientation:      'Landscape'
  margin-top:       '18mm'
  margin-bottom:    '15mm'
  margin-left:      '10mm'
  margin-right:     '10mm'
  no-stop-slow-scripts: True
  javascript-delay: '5000'

reports:
  invest:
    data:
      source_type:     'api'
      source:   'http://localhost:3000/invest'
    template:
      location: 'invest.html'
  capital:
    data:
      source_type:     'api'
      source:   'http://localhost:3000/capital'
    template:
      location: 'capital.html'
  cars_phl_api:
    data:
      source_type: api
      name: car_accident_phl
      source: >-
        https://phl.carto.com/api/v2/sql?q=
        SELECT%20crash_year,
        %20sum(fatal_count)%20AS%20fatal,
        %20sum(injury_count)%20AS%20injury,
        %20sum(bicycle_count)%20as%20bike_crash
        %20FROM%20crash_data_collision_crash_2007_2017%20
        %20GROUP%20BY%201
    template:
      location: car_accidents.html
  cars_phl_sql:
    data:
      - name: sql 
        source_type: sqlite
        source:     './tmp/phl_crash_data.db'
        query: >-
          select crash_year,
            fatal,
            injury,
            bike_crash
          from crash_by_year
      - name: text
        source_type: text
        source: "This is data from 2011 to 2017."
    template:
      location: car_accidents_v2.html
