PDF:
  encoding:       'UTF-8'
  page-size:      'Letter'
  orientation:    'Landscape'
  margin-top:     '18mm'
  margin-bottom:  '15mm'
  margin-left:    '10mm'
  margin-right:   '10mm'

Templates:
  invest:
    end_point: 'http://localhost:3000/invest'
    template_loc: 'invest.html'
  capital:
    end_point: 'http://localhost:3000/capital'
    template_loc: 'capital.html'
